version: '3.3'

services:
  db1:
    image: mysql:5.7
    environment:
      # Datenbank die mit erzeugt werden soll (Schema), Achtung: case-sensitive in Java
      MYSQL_DATABASE: 'test'
      # Neuer user root2, der nur für die angelegte DB alle Rechte hat
      MYSQL_USER: 'root2'
      # Passwort für den neu angelegten user root2
      MYSQL_PASSWORD: '1234'
      # Passwort für den Standardbenutzer root setzen (dieser User hat alle Rechte im Server)
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db1:/var/lib/mysql1

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
# Names our volume
volumes:
  my-db1: